
###############################################################################

# Date    : 10. 03. 2015.
# Company : Xylon d.o.o.
# URL     : https://www.logicbricks.com

# Title   : ZedBoard Base TRD reference design constraints
# Tool    : Vivado 2014.4

###############################################################################

###############################################################################
# Primary Clocks
###############################################################################

# Constrained to 148.5 MHz (1080p60 video resolution)
create_clock -period 6.667 -name clk0 -waveform {0.000 3.333} [get_nets *clk0_drp -hierarchical]

# Single-ended input clock from HDMI input
# Constrained to 148.5 MHz (1080p60 video resolution)
create_clock -period 6.734 -name hdmii_clk [get_ports fmc_imageon_hdmii_clk]

###############################################################################
# Generated Clocks
###############################################################################

# Axi-lite clock 50 MHz
create_generated_clock -name clk50 [get_pins zedboard_btrd_i/clk_wiz_1/U0/mmcm_adv_inst/CLKOUT0]

# AXI Stream and MemoryMap clock 150 MHz
create_generated_clock -name clk150 [get_pins zedboard_btrd_i/clk_wiz_1/U0/mmcm_adv_inst/CLKOUT1]

###############################################################################
# Clock Groups
###############################################################################

# clk0 is generated by logiclk DRP clock synthesizer and clk50/clk150 by Clock Wizard PLL
# There is no known phase relationship, hence they are treated as asynchronous

set_clock_groups -asynchronous -group {clk50 clk150} -group clk0

# BUFGMUX selects one of the two external clocks for the video capture pipeline
# The two clocks are physically exclusive since they don't exist at the same time

set_clock_groups -physically_exclusive -group hdmii_clk -group clk0

###############################################################################
# Timing Exceptions
###############################################################################

# Use fastest clock of the BUFGMUX as the path that timing analysis should be done on
# In this case, both clocks have the same period constraint, so either input 0 or input 1 can be selected

set_case_analysis 0 [get_pins zedboard_btrd_i/fmc_hdmi_input/clock_mux_1/sel]

###############################################################################
# Physical Constraints
###############################################################################

# OTG USB PHY RESET

set_property IOSTANDARD LVCMOS25 [get_ports otg_reset_n]
set_property PACKAGE_PIN G17 [get_ports otg_reset_n]

# HDMI Output (ADV7511) on ZedBoard

set_property PACKAGE_PIN W16 [get_ports hdmio_int_b]

set_property PACKAGE_PIN W18 [get_ports hdmio_clk]
set_property PACKAGE_PIN V17 [get_ports hdmio_hsync]
set_property PACKAGE_PIN W17 [get_ports hdmio_vsync]
set_property PACKAGE_PIN U16 [get_ports hdmio_active_video]

set_property PACKAGE_PIN Y13 [get_ports {hdmio_data[0]}]
set_property PACKAGE_PIN AA13 [get_ports {hdmio_data[1]}]
set_property PACKAGE_PIN AA14 [get_ports {hdmio_data[2]}]
set_property PACKAGE_PIN Y14 [get_ports {hdmio_data[3]}]
set_property PACKAGE_PIN AB15 [get_ports {hdmio_data[4]}]
set_property PACKAGE_PIN AB16 [get_ports {hdmio_data[5]}]
set_property PACKAGE_PIN AA16 [get_ports {hdmio_data[6]}]
set_property PACKAGE_PIN AB17 [get_ports {hdmio_data[7]}]
set_property PACKAGE_PIN AA17 [get_ports {hdmio_data[8]}]
set_property PACKAGE_PIN Y15 [get_ports {hdmio_data[9]}]
set_property PACKAGE_PIN W13 [get_ports {hdmio_data[10]}]
set_property PACKAGE_PIN W15 [get_ports {hdmio_data[11]}]
set_property PACKAGE_PIN V15 [get_ports {hdmio_data[12]}]
set_property PACKAGE_PIN U17 [get_ports {hdmio_data[13]}]
set_property PACKAGE_PIN V14 [get_ports {hdmio_data[14]}]
set_property PACKAGE_PIN V13 [get_ports {hdmio_data[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports hdmio_*]

set_property IOB TRUE [get_cells -hierarchical YCbCr_4_2_2_gen.*_o_reg*]

# I2C Chain 1 for HDMI encoder

set_property IOSTANDARD LVCMOS25 [get_ports iic_0_scl_io]
set_property PACKAGE_PIN AA18 [get_ports iic_0_scl_io]
set_property PULLUP true [get_ports iic_0_scl_io]
set_property IOSTANDARD LVCMOS25 [get_ports iic_0_sda_io]
set_property PACKAGE_PIN Y16 [get_ports iic_0_sda_io]
set_property PULLUP true [get_ports iic_0_sda_io]

# I2C Chain 2 on FMC-IMAGEON on ZedBoard

set_property PACKAGE_PIN J20 [get_ports fmc_imageon_iic_scl_io]
set_property PACKAGE_PIN K21 [get_ports fmc_imageon_iic_sda_io]
set_property PACKAGE_PIN N20 [get_ports {fmc_imageon_iic_rst_b[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports fmc_imageon_iic_*]

# HDMI Input (ADV7611) on FMC-IMAGEON on ZedBoard

set_property PACKAGE_PIN D18 [get_ports fmc_imageon_hdmii_clk]
set_property IOSTANDARD LVCMOS25 [get_ports fmc_imageon_hdmii_clk]

set_property PACKAGE_PIN A22 [get_ports {IO_HDMII_data[0]}]
set_property PACKAGE_PIN A21 [get_ports {IO_HDMII_data[1]}]
set_property PACKAGE_PIN B22 [get_ports {IO_HDMII_data[2]}]
set_property PACKAGE_PIN B21 [get_ports {IO_HDMII_data[3]}]
set_property PACKAGE_PIN B15 [get_ports {IO_HDMII_data[4]}]
set_property PACKAGE_PIN C15 [get_ports {IO_HDMII_data[5]}]
set_property PACKAGE_PIN B17 [get_ports {IO_HDMII_data[6]}]
set_property PACKAGE_PIN B16 [get_ports {IO_HDMII_data[7]}]
set_property PACKAGE_PIN A17 [get_ports {IO_HDMII_data[8]}]
set_property PACKAGE_PIN A16 [get_ports {IO_HDMII_data[9]}]
set_property PACKAGE_PIN C18 [get_ports {IO_HDMII_data[10]}]
set_property PACKAGE_PIN D21 [get_ports {IO_HDMII_data[11]}]
set_property PACKAGE_PIN E18 [get_ports {IO_HDMII_data[12]}]
set_property PACKAGE_PIN C17 [get_ports {IO_HDMII_data[13]}]
set_property PACKAGE_PIN E21 [get_ports {IO_HDMII_data[14]}]
set_property PACKAGE_PIN F18 [get_ports {IO_HDMII_data[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports IO_HDMII_*]
