// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module image_filter_top (
s_axi_CONTROL_BUS_AWADDR,
s_axi_CONTROL_BUS_AWVALID,
s_axi_CONTROL_BUS_AWREADY,
s_axi_CONTROL_BUS_WDATA,
s_axi_CONTROL_BUS_WSTRB,
s_axi_CONTROL_BUS_WVALID,
s_axi_CONTROL_BUS_WREADY,
s_axi_CONTROL_BUS_BRESP,
s_axi_CONTROL_BUS_BVALID,
s_axi_CONTROL_BUS_BREADY,
s_axi_CONTROL_BUS_ARADDR,
s_axi_CONTROL_BUS_ARVALID,
s_axi_CONTROL_BUS_ARREADY,
s_axi_CONTROL_BUS_RDATA,
s_axi_CONTROL_BUS_RRESP,
s_axi_CONTROL_BUS_RVALID,
s_axi_CONTROL_BUS_RREADY,
interrupt,
INPUT_STREAM_TVALID,
INPUT_STREAM_TREADY,
INPUT_STREAM_TDATA,
INPUT_STREAM_TKEEP,
INPUT_STREAM_TSTRB,
INPUT_STREAM_TUSER,
INPUT_STREAM_TLAST,
INPUT_STREAM_TID,
INPUT_STREAM_TDEST,
OUTPUT_STREAM_TVALID,
OUTPUT_STREAM_TREADY,
OUTPUT_STREAM_TDATA,
OUTPUT_STREAM_TKEEP,
OUTPUT_STREAM_TSTRB,
OUTPUT_STREAM_TUSER,
OUTPUT_STREAM_TLAST,
OUTPUT_STREAM_TID,
OUTPUT_STREAM_TDEST,
aresetn,
aclk
);

parameter C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 8;
parameter C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32;
parameter RESET_ACTIVE_LOW = 1;

input [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_AWADDR ;
input s_axi_CONTROL_BUS_AWVALID ;
output s_axi_CONTROL_BUS_AWREADY ;
input [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_WDATA ;
input [C_S_AXI_CONTROL_BUS_DATA_WIDTH/8 - 1:0] s_axi_CONTROL_BUS_WSTRB ;
input s_axi_CONTROL_BUS_WVALID ;
output s_axi_CONTROL_BUS_WREADY ;
output [2 - 1:0] s_axi_CONTROL_BUS_BRESP ;
output s_axi_CONTROL_BUS_BVALID ;
input s_axi_CONTROL_BUS_BREADY ;
input [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_ARADDR ;
input s_axi_CONTROL_BUS_ARVALID ;
output s_axi_CONTROL_BUS_ARREADY ;
output [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_RDATA ;
output [2 - 1:0] s_axi_CONTROL_BUS_RRESP ;
output s_axi_CONTROL_BUS_RVALID ;
input s_axi_CONTROL_BUS_RREADY ;
output interrupt ;


input INPUT_STREAM_TVALID ;
output INPUT_STREAM_TREADY ;
input [16 - 1:0] INPUT_STREAM_TDATA ;
input [2 - 1:0] INPUT_STREAM_TKEEP ;
input [2 - 1:0] INPUT_STREAM_TSTRB ;
input [1 - 1:0] INPUT_STREAM_TUSER ;
input [1 - 1:0] INPUT_STREAM_TLAST ;
input [1 - 1:0] INPUT_STREAM_TID ;
input [1 - 1:0] INPUT_STREAM_TDEST ;


output OUTPUT_STREAM_TVALID ;
input OUTPUT_STREAM_TREADY ;
output [16 - 1:0] OUTPUT_STREAM_TDATA ;
output [2 - 1:0] OUTPUT_STREAM_TKEEP ;
output [2 - 1:0] OUTPUT_STREAM_TSTRB ;
output [1 - 1:0] OUTPUT_STREAM_TUSER ;
output [1 - 1:0] OUTPUT_STREAM_TLAST ;
output [1 - 1:0] OUTPUT_STREAM_TID ;
output [1 - 1:0] OUTPUT_STREAM_TDEST ;

input aresetn ;

input aclk ;


wire [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_AWADDR;
wire s_axi_CONTROL_BUS_AWVALID;
wire s_axi_CONTROL_BUS_AWREADY;
wire [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_WDATA;
wire [C_S_AXI_CONTROL_BUS_DATA_WIDTH/8 - 1:0] s_axi_CONTROL_BUS_WSTRB;
wire s_axi_CONTROL_BUS_WVALID;
wire s_axi_CONTROL_BUS_WREADY;
wire [2 - 1:0] s_axi_CONTROL_BUS_BRESP;
wire s_axi_CONTROL_BUS_BVALID;
wire s_axi_CONTROL_BUS_BREADY;
wire [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_ARADDR;
wire s_axi_CONTROL_BUS_ARVALID;
wire s_axi_CONTROL_BUS_ARREADY;
wire [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_RDATA;
wire [2 - 1:0] s_axi_CONTROL_BUS_RRESP;
wire s_axi_CONTROL_BUS_RVALID;
wire s_axi_CONTROL_BUS_RREADY;
wire interrupt;


wire INPUT_STREAM_TVALID;
wire INPUT_STREAM_TREADY;
wire [16 - 1:0] INPUT_STREAM_TDATA;
wire [2 - 1:0] INPUT_STREAM_TKEEP;
wire [2 - 1:0] INPUT_STREAM_TSTRB;
wire [1 - 1:0] INPUT_STREAM_TUSER;
wire [1 - 1:0] INPUT_STREAM_TLAST;
wire [1 - 1:0] INPUT_STREAM_TID;
wire [1 - 1:0] INPUT_STREAM_TDEST;


wire OUTPUT_STREAM_TVALID;
wire OUTPUT_STREAM_TREADY;
wire [16 - 1:0] OUTPUT_STREAM_TDATA;
wire [2 - 1:0] OUTPUT_STREAM_TKEEP;
wire [2 - 1:0] OUTPUT_STREAM_TSTRB;
wire [1 - 1:0] OUTPUT_STREAM_TUSER;
wire [1 - 1:0] OUTPUT_STREAM_TLAST;
wire [1 - 1:0] OUTPUT_STREAM_TID;
wire [1 - 1:0] OUTPUT_STREAM_TDEST;

wire aresetn;


wire [32 - 1:0] sig_image_filter_rows;
wire [32 - 1:0] sig_image_filter_cols;
wire [32 - 1:0] sig_image_filter_C_XR0C0;
wire [32 - 1:0] sig_image_filter_C_XR0C1;
wire [32 - 1:0] sig_image_filter_C_XR0C2;
wire [32 - 1:0] sig_image_filter_C_XR1C0;
wire [32 - 1:0] sig_image_filter_C_XR1C1;
wire [32 - 1:0] sig_image_filter_C_XR1C2;
wire [32 - 1:0] sig_image_filter_C_XR2C0;
wire [32 - 1:0] sig_image_filter_C_XR2C1;
wire [32 - 1:0] sig_image_filter_C_XR2C2;
wire [32 - 1:0] sig_image_filter_C_YR0C0;
wire [32 - 1:0] sig_image_filter_C_YR0C1;
wire [32 - 1:0] sig_image_filter_C_YR0C2;
wire [32 - 1:0] sig_image_filter_C_YR1C0;
wire [32 - 1:0] sig_image_filter_C_YR1C1;
wire [32 - 1:0] sig_image_filter_C_YR1C2;
wire [32 - 1:0] sig_image_filter_C_YR2C0;
wire [32 - 1:0] sig_image_filter_C_YR2C1;
wire [32 - 1:0] sig_image_filter_C_YR2C2;
wire [32 - 1:0] sig_image_filter_c_high_thesh;
wire [32 - 1:0] sig_image_filter_c_low_thresh;
wire [32 - 1:0] sig_image_filter_c_invert;
wire sig_image_filter_ap_start;
wire sig_image_filter_ap_ready;
wire sig_image_filter_ap_done;
wire sig_image_filter_ap_idle;

wire [16 - 1:0] sig_image_filter_axi_src_V_data_V_dout;
wire sig_image_filter_axi_src_V_data_V_empty_n;
wire sig_image_filter_axi_src_V_data_V_read;
wire [2 - 1:0] sig_image_filter_axi_src_V_keep_V_dout;
wire sig_image_filter_axi_src_V_keep_V_empty_n;
wire sig_image_filter_axi_src_V_keep_V_read;
wire [2 - 1:0] sig_image_filter_axi_src_V_strb_V_dout;
wire sig_image_filter_axi_src_V_strb_V_empty_n;
wire sig_image_filter_axi_src_V_strb_V_read;
wire [1 - 1:0] sig_image_filter_axi_src_V_user_V_dout;
wire sig_image_filter_axi_src_V_user_V_empty_n;
wire sig_image_filter_axi_src_V_user_V_read;
wire [1 - 1:0] sig_image_filter_axi_src_V_last_V_dout;
wire sig_image_filter_axi_src_V_last_V_empty_n;
wire sig_image_filter_axi_src_V_last_V_read;
wire [1 - 1:0] sig_image_filter_axi_src_V_id_V_dout;
wire sig_image_filter_axi_src_V_id_V_empty_n;
wire sig_image_filter_axi_src_V_id_V_read;
wire [1 - 1:0] sig_image_filter_axi_src_V_dest_V_dout;
wire sig_image_filter_axi_src_V_dest_V_empty_n;
wire sig_image_filter_axi_src_V_dest_V_read;

wire [16 - 1:0] sig_image_filter_axi_dst_V_data_V_din;
wire sig_image_filter_axi_dst_V_data_V_full_n;
wire sig_image_filter_axi_dst_V_data_V_write;
wire [2 - 1:0] sig_image_filter_axi_dst_V_keep_V_din;
wire sig_image_filter_axi_dst_V_keep_V_full_n;
wire sig_image_filter_axi_dst_V_keep_V_write;
wire [2 - 1:0] sig_image_filter_axi_dst_V_strb_V_din;
wire sig_image_filter_axi_dst_V_strb_V_full_n;
wire sig_image_filter_axi_dst_V_strb_V_write;
wire [1 - 1:0] sig_image_filter_axi_dst_V_user_V_din;
wire sig_image_filter_axi_dst_V_user_V_full_n;
wire sig_image_filter_axi_dst_V_user_V_write;
wire [1 - 1:0] sig_image_filter_axi_dst_V_last_V_din;
wire sig_image_filter_axi_dst_V_last_V_full_n;
wire sig_image_filter_axi_dst_V_last_V_write;
wire [1 - 1:0] sig_image_filter_axi_dst_V_id_V_din;
wire sig_image_filter_axi_dst_V_id_V_full_n;
wire sig_image_filter_axi_dst_V_id_V_write;
wire [1 - 1:0] sig_image_filter_axi_dst_V_dest_V_din;
wire sig_image_filter_axi_dst_V_dest_V_full_n;
wire sig_image_filter_axi_dst_V_dest_V_write;

wire sig_image_filter_ap_rst;



image_filter image_filter_U(
    .rows(sig_image_filter_rows),
    .cols(sig_image_filter_cols),
    .C_XR0C0(sig_image_filter_C_XR0C0),
    .C_XR0C1(sig_image_filter_C_XR0C1),
    .C_XR0C2(sig_image_filter_C_XR0C2),
    .C_XR1C0(sig_image_filter_C_XR1C0),
    .C_XR1C1(sig_image_filter_C_XR1C1),
    .C_XR1C2(sig_image_filter_C_XR1C2),
    .C_XR2C0(sig_image_filter_C_XR2C0),
    .C_XR2C1(sig_image_filter_C_XR2C1),
    .C_XR2C2(sig_image_filter_C_XR2C2),
    .C_YR0C0(sig_image_filter_C_YR0C0),
    .C_YR0C1(sig_image_filter_C_YR0C1),
    .C_YR0C2(sig_image_filter_C_YR0C2),
    .C_YR1C0(sig_image_filter_C_YR1C0),
    .C_YR1C1(sig_image_filter_C_YR1C1),
    .C_YR1C2(sig_image_filter_C_YR1C2),
    .C_YR2C0(sig_image_filter_C_YR2C0),
    .C_YR2C1(sig_image_filter_C_YR2C1),
    .C_YR2C2(sig_image_filter_C_YR2C2),
    .c_high_thesh(sig_image_filter_c_high_thesh),
    .c_low_thresh(sig_image_filter_c_low_thresh),
    .c_invert(sig_image_filter_c_invert),
    .ap_start(sig_image_filter_ap_start),
    .ap_ready(sig_image_filter_ap_ready),
    .ap_done(sig_image_filter_ap_done),
    .ap_idle(sig_image_filter_ap_idle),
    .axi_src_V_data_V_dout(sig_image_filter_axi_src_V_data_V_dout),
    .axi_src_V_data_V_empty_n(sig_image_filter_axi_src_V_data_V_empty_n),
    .axi_src_V_data_V_read(sig_image_filter_axi_src_V_data_V_read),
    .axi_src_V_keep_V_dout(sig_image_filter_axi_src_V_keep_V_dout),
    .axi_src_V_keep_V_empty_n(sig_image_filter_axi_src_V_keep_V_empty_n),
    .axi_src_V_keep_V_read(sig_image_filter_axi_src_V_keep_V_read),
    .axi_src_V_strb_V_dout(sig_image_filter_axi_src_V_strb_V_dout),
    .axi_src_V_strb_V_empty_n(sig_image_filter_axi_src_V_strb_V_empty_n),
    .axi_src_V_strb_V_read(sig_image_filter_axi_src_V_strb_V_read),
    .axi_src_V_user_V_dout(sig_image_filter_axi_src_V_user_V_dout),
    .axi_src_V_user_V_empty_n(sig_image_filter_axi_src_V_user_V_empty_n),
    .axi_src_V_user_V_read(sig_image_filter_axi_src_V_user_V_read),
    .axi_src_V_last_V_dout(sig_image_filter_axi_src_V_last_V_dout),
    .axi_src_V_last_V_empty_n(sig_image_filter_axi_src_V_last_V_empty_n),
    .axi_src_V_last_V_read(sig_image_filter_axi_src_V_last_V_read),
    .axi_src_V_id_V_dout(sig_image_filter_axi_src_V_id_V_dout),
    .axi_src_V_id_V_empty_n(sig_image_filter_axi_src_V_id_V_empty_n),
    .axi_src_V_id_V_read(sig_image_filter_axi_src_V_id_V_read),
    .axi_src_V_dest_V_dout(sig_image_filter_axi_src_V_dest_V_dout),
    .axi_src_V_dest_V_empty_n(sig_image_filter_axi_src_V_dest_V_empty_n),
    .axi_src_V_dest_V_read(sig_image_filter_axi_src_V_dest_V_read),
    .axi_dst_V_data_V_din(sig_image_filter_axi_dst_V_data_V_din),
    .axi_dst_V_data_V_full_n(sig_image_filter_axi_dst_V_data_V_full_n),
    .axi_dst_V_data_V_write(sig_image_filter_axi_dst_V_data_V_write),
    .axi_dst_V_keep_V_din(sig_image_filter_axi_dst_V_keep_V_din),
    .axi_dst_V_keep_V_full_n(sig_image_filter_axi_dst_V_keep_V_full_n),
    .axi_dst_V_keep_V_write(sig_image_filter_axi_dst_V_keep_V_write),
    .axi_dst_V_strb_V_din(sig_image_filter_axi_dst_V_strb_V_din),
    .axi_dst_V_strb_V_full_n(sig_image_filter_axi_dst_V_strb_V_full_n),
    .axi_dst_V_strb_V_write(sig_image_filter_axi_dst_V_strb_V_write),
    .axi_dst_V_user_V_din(sig_image_filter_axi_dst_V_user_V_din),
    .axi_dst_V_user_V_full_n(sig_image_filter_axi_dst_V_user_V_full_n),
    .axi_dst_V_user_V_write(sig_image_filter_axi_dst_V_user_V_write),
    .axi_dst_V_last_V_din(sig_image_filter_axi_dst_V_last_V_din),
    .axi_dst_V_last_V_full_n(sig_image_filter_axi_dst_V_last_V_full_n),
    .axi_dst_V_last_V_write(sig_image_filter_axi_dst_V_last_V_write),
    .axi_dst_V_id_V_din(sig_image_filter_axi_dst_V_id_V_din),
    .axi_dst_V_id_V_full_n(sig_image_filter_axi_dst_V_id_V_full_n),
    .axi_dst_V_id_V_write(sig_image_filter_axi_dst_V_id_V_write),
    .axi_dst_V_dest_V_din(sig_image_filter_axi_dst_V_dest_V_din),
    .axi_dst_V_dest_V_full_n(sig_image_filter_axi_dst_V_dest_V_full_n),
    .axi_dst_V_dest_V_write(sig_image_filter_axi_dst_V_dest_V_write),
    .ap_rst(sig_image_filter_ap_rst),
    .ap_clk(aclk)
);

image_filter_CONTROL_BUS_if #(
    .C_ADDR_WIDTH(C_S_AXI_CONTROL_BUS_ADDR_WIDTH),
    .C_DATA_WIDTH(C_S_AXI_CONTROL_BUS_DATA_WIDTH))
image_filter_CONTROL_BUS_if_U(
    .ACLK(aclk),
    .ARESETN(aresetn),
    .I_rows(sig_image_filter_rows),
    .I_cols(sig_image_filter_cols),
    .I_C_XR0C0(sig_image_filter_C_XR0C0),
    .I_C_XR0C1(sig_image_filter_C_XR0C1),
    .I_C_XR0C2(sig_image_filter_C_XR0C2),
    .I_C_XR1C0(sig_image_filter_C_XR1C0),
    .I_C_XR1C1(sig_image_filter_C_XR1C1),
    .I_C_XR1C2(sig_image_filter_C_XR1C2),
    .I_C_XR2C0(sig_image_filter_C_XR2C0),
    .I_C_XR2C1(sig_image_filter_C_XR2C1),
    .I_C_XR2C2(sig_image_filter_C_XR2C2),
    .I_C_YR0C0(sig_image_filter_C_YR0C0),
    .I_C_YR0C1(sig_image_filter_C_YR0C1),
    .I_C_YR0C2(sig_image_filter_C_YR0C2),
    .I_C_YR1C0(sig_image_filter_C_YR1C0),
    .I_C_YR1C1(sig_image_filter_C_YR1C1),
    .I_C_YR1C2(sig_image_filter_C_YR1C2),
    .I_C_YR2C0(sig_image_filter_C_YR2C0),
    .I_C_YR2C1(sig_image_filter_C_YR2C1),
    .I_C_YR2C2(sig_image_filter_C_YR2C2),
    .I_c_high_thesh(sig_image_filter_c_high_thesh),
    .I_c_low_thresh(sig_image_filter_c_low_thresh),
    .I_c_invert(sig_image_filter_c_invert),
    .I_ap_start(sig_image_filter_ap_start),
    .O_ap_ready(sig_image_filter_ap_ready),
    .O_ap_done(sig_image_filter_ap_done),
    .O_ap_idle(sig_image_filter_ap_idle),
    .AWADDR(s_axi_CONTROL_BUS_AWADDR),
    .AWVALID(s_axi_CONTROL_BUS_AWVALID),
    .AWREADY(s_axi_CONTROL_BUS_AWREADY),
    .WDATA(s_axi_CONTROL_BUS_WDATA),
    .WSTRB(s_axi_CONTROL_BUS_WSTRB),
    .WVALID(s_axi_CONTROL_BUS_WVALID),
    .WREADY(s_axi_CONTROL_BUS_WREADY),
    .BRESP(s_axi_CONTROL_BUS_BRESP),
    .BVALID(s_axi_CONTROL_BUS_BVALID),
    .BREADY(s_axi_CONTROL_BUS_BREADY),
    .ARADDR(s_axi_CONTROL_BUS_ARADDR),
    .ARVALID(s_axi_CONTROL_BUS_ARVALID),
    .ARREADY(s_axi_CONTROL_BUS_ARREADY),
    .RDATA(s_axi_CONTROL_BUS_RDATA),
    .RRESP(s_axi_CONTROL_BUS_RRESP),
    .RVALID(s_axi_CONTROL_BUS_RVALID),
    .RREADY(s_axi_CONTROL_BUS_RREADY),
    .interrupt(interrupt));

image_filter_INPUT_STREAM_if image_filter_INPUT_STREAM_if_U(
    .ACLK(aclk),
    .ARESETN(aresetn),
    .axi_src_V_data_V_dout(sig_image_filter_axi_src_V_data_V_dout),
    .axi_src_V_data_V_empty_n(sig_image_filter_axi_src_V_data_V_empty_n),
    .axi_src_V_data_V_read(sig_image_filter_axi_src_V_data_V_read),
    .axi_src_V_keep_V_dout(sig_image_filter_axi_src_V_keep_V_dout),
    .axi_src_V_keep_V_empty_n(sig_image_filter_axi_src_V_keep_V_empty_n),
    .axi_src_V_keep_V_read(sig_image_filter_axi_src_V_keep_V_read),
    .axi_src_V_strb_V_dout(sig_image_filter_axi_src_V_strb_V_dout),
    .axi_src_V_strb_V_empty_n(sig_image_filter_axi_src_V_strb_V_empty_n),
    .axi_src_V_strb_V_read(sig_image_filter_axi_src_V_strb_V_read),
    .axi_src_V_user_V_dout(sig_image_filter_axi_src_V_user_V_dout),
    .axi_src_V_user_V_empty_n(sig_image_filter_axi_src_V_user_V_empty_n),
    .axi_src_V_user_V_read(sig_image_filter_axi_src_V_user_V_read),
    .axi_src_V_last_V_dout(sig_image_filter_axi_src_V_last_V_dout),
    .axi_src_V_last_V_empty_n(sig_image_filter_axi_src_V_last_V_empty_n),
    .axi_src_V_last_V_read(sig_image_filter_axi_src_V_last_V_read),
    .axi_src_V_id_V_dout(sig_image_filter_axi_src_V_id_V_dout),
    .axi_src_V_id_V_empty_n(sig_image_filter_axi_src_V_id_V_empty_n),
    .axi_src_V_id_V_read(sig_image_filter_axi_src_V_id_V_read),
    .axi_src_V_dest_V_dout(sig_image_filter_axi_src_V_dest_V_dout),
    .axi_src_V_dest_V_empty_n(sig_image_filter_axi_src_V_dest_V_empty_n),
    .axi_src_V_dest_V_read(sig_image_filter_axi_src_V_dest_V_read),
    .TVALID(INPUT_STREAM_TVALID),
    .TREADY(INPUT_STREAM_TREADY),
    .TDATA(INPUT_STREAM_TDATA),
    .TKEEP(INPUT_STREAM_TKEEP),
    .TSTRB(INPUT_STREAM_TSTRB),
    .TUSER(INPUT_STREAM_TUSER),
    .TLAST(INPUT_STREAM_TLAST),
    .TID(INPUT_STREAM_TID),
    .TDEST(INPUT_STREAM_TDEST));

image_filter_OUTPUT_STREAM_if image_filter_OUTPUT_STREAM_if_U(
    .ACLK(aclk),
    .ARESETN(aresetn),
    .axi_dst_V_data_V_din(sig_image_filter_axi_dst_V_data_V_din),
    .axi_dst_V_data_V_full_n(sig_image_filter_axi_dst_V_data_V_full_n),
    .axi_dst_V_data_V_write(sig_image_filter_axi_dst_V_data_V_write),
    .axi_dst_V_keep_V_din(sig_image_filter_axi_dst_V_keep_V_din),
    .axi_dst_V_keep_V_full_n(sig_image_filter_axi_dst_V_keep_V_full_n),
    .axi_dst_V_keep_V_write(sig_image_filter_axi_dst_V_keep_V_write),
    .axi_dst_V_strb_V_din(sig_image_filter_axi_dst_V_strb_V_din),
    .axi_dst_V_strb_V_full_n(sig_image_filter_axi_dst_V_strb_V_full_n),
    .axi_dst_V_strb_V_write(sig_image_filter_axi_dst_V_strb_V_write),
    .axi_dst_V_user_V_din(sig_image_filter_axi_dst_V_user_V_din),
    .axi_dst_V_user_V_full_n(sig_image_filter_axi_dst_V_user_V_full_n),
    .axi_dst_V_user_V_write(sig_image_filter_axi_dst_V_user_V_write),
    .axi_dst_V_last_V_din(sig_image_filter_axi_dst_V_last_V_din),
    .axi_dst_V_last_V_full_n(sig_image_filter_axi_dst_V_last_V_full_n),
    .axi_dst_V_last_V_write(sig_image_filter_axi_dst_V_last_V_write),
    .axi_dst_V_id_V_din(sig_image_filter_axi_dst_V_id_V_din),
    .axi_dst_V_id_V_full_n(sig_image_filter_axi_dst_V_id_V_full_n),
    .axi_dst_V_id_V_write(sig_image_filter_axi_dst_V_id_V_write),
    .axi_dst_V_dest_V_din(sig_image_filter_axi_dst_V_dest_V_din),
    .axi_dst_V_dest_V_full_n(sig_image_filter_axi_dst_V_dest_V_full_n),
    .axi_dst_V_dest_V_write(sig_image_filter_axi_dst_V_dest_V_write),
    .TVALID(OUTPUT_STREAM_TVALID),
    .TREADY(OUTPUT_STREAM_TREADY),
    .TDATA(OUTPUT_STREAM_TDATA),
    .TKEEP(OUTPUT_STREAM_TKEEP),
    .TSTRB(OUTPUT_STREAM_TSTRB),
    .TUSER(OUTPUT_STREAM_TUSER),
    .TLAST(OUTPUT_STREAM_TLAST),
    .TID(OUTPUT_STREAM_TID),
    .TDEST(OUTPUT_STREAM_TDEST));

image_filter_ap_rst_if #(
    .RESET_ACTIVE_LOW(RESET_ACTIVE_LOW))
ap_rst_if_U(
    .dout(sig_image_filter_ap_rst),
    .din(aresetn));

endmodule
